#!/usr/bin/env bash
# Script that transfers a file from client to server



if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	path=$1
	ip=$2
	uname=$3
	kpath=$4
	d_name="$uname@$ip"

	scp -o StrictHostKeyChecking=No  -i "$kpath" "$path" "$d_name":~/
fi
