#!/usr/bin/env bash
# script that installs nginx on server

#run updates
sudo apt update
# sudo apt upgrade -y
sudo apt install -y nginx

sudo service nginx start

# Create HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

#configure /redirect_me to return 301

former_tag="server_name _;"

new_tag="\n\tlocation = \/redirect_me {\n\t\treturn 301;\n\t}"

replacement_tag="$former_tag$new_tag"
sudo sed -z -i "s/server_name _;\n/$replacement_tag/" /etc/nginx/sites-enabled/default

# Restart Nginx
sudo nginx -t -q && sudo nginx -s reload
