#!/usr/bin/env bash
# Script that installs new nginx server

sudo apt update && sudo apt install -y nginx

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default

sudo service nginx reload
