#!/usr/bin/env bash
# Configure server with custom header

sudo apt update && sudo apt install nginx -y


sudo service nginx start

# Create HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

#configure /redirect_me to return 301

former_tag="server_name _;"

new_tag="\n\tlocation = \/redirect_me {\n\t\treturn 301;\n\t}"

replacement_tag="$former_tag$new_tag"
sudo sed -z -i "s/server_name _;\n/$replacement_tag/" /etc/nginx/sites-enabled/default

# error 404 setting

#create directory
sudo mkdir /var/www/html/err
# create error 404 file
sudo touch /var/www/html/err/error404.html

# echo error message into error 404 file
echo "Ceci n'est pas une page" | sudo tee /var/www/html/err/error404.html > /dev/null

former_tag="\t\ttry_files \$uri \$uri\/ =404;\n\t}"

new_tag="\t\ttry_files \$uri \$uri\/ =404;\n\t}\n\n\terror_page 404 \/err\/error404.html;\n"


# configure conf file to include error file
replacement_tag="$new_tag"
sudo sed -z -i "s/$former_tag/$replacement_tag/" /etc/nginx/sites-enabled/default

sudo sed -i "0,/root \/var\/www\/html;/s//root \/var\/www\/html;\n\n\tadd_header X-Served-By \$hostname;/" /etc/nginx/sites-enabled/default

sudo nginx -t -q && sudo nginx -s reload
