#!/usr/bin/env bash
#configures a loadbalancer

#update & installation
sudo apt update && sudo apt install -y haproxy

# allows for HAproxy to be managed via init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null

#moves original cfg file to .original extension
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo cp /etc/haproxy/haproxy.cfg.original /etc/haproxy/haproxy.cfg

# server config
input=$(cat <<EOF

frontend web-frontend
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web-01 100.26.152.138:80 check
        server web-02 100.25.33.164:80 check
EOF
)

echo "$input" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# restart service
sudo systemctl restart haproxy
