#!/usr/bin/env bash
# Installs and configures HAproxy in a load balancer server

# apt-get update
# apt-get install -y haproxy

# echo "ENABLED=1" >> /etc/default/haproxy

haproxy_config=$(cat <<EOF

frontend web-frontend
   #bind *:443 crt /etc/ssl/private/test.pem
   bind *:80
   mode http
   #http-request set-header X-Forwarded-Proto https
   stats uri /haproxy?stats
   default_backend web_backend

backend web_backend
   mode http
   balance roundrobin
   server web-01 100.26.152.138:80 check
   server web-02 100.25.33.164:80 check
EOF
)

echo "$haproxy_config"
# | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# systemctl start haproxy
# systemctl enable haproxy
