#!/usr/bin/env bash
# printing the time for 12 hours & 59 minutes

x=0;
# time="Hour:";
# symbol=45;
while [ $x -le 12 ]
do
	echo "Hour: $x"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		minute=$(( minute + 1 ))
	done
	#echo "Hi"
	x=$(( x + 1 ))
done
